---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - python3-pip
      - openssh-server
      - scdaemon
      - paperkey
      - stow
      - zsh
      - fzf
      - zoxide
      - exa
      - tmux
      - tree
      - pass
      - pwgen
      - sqlite3
      - libssl-dev
      - postgresql-13
      - ripgrep
      - rsync
      - ncdu
      - ufw
      - libpam-yubico
      - libyubikey-dev
      - yubikey-personalization
      - yubikey-luks
      - wireshark
      - ninja-build
      - gettext
      - cmake
