---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - python3-pip
      - openssh-server
      - scdaemon
      - paperkey
      - stow
      - zsh
      - fzf
      - zoxide
      - exa
      - tmux
      - tree
      - pass
      - pwgen
      - sqlite3
      - libssl-dev
      - postgresql-13
      - ripgrep
      - rsync
      - librsync-dev
      - ncdu
      - ufw
      - nmap
      - libpam-yubico
      - libyubikey-dev
      - yubikey-personalization
      - yubikey-luks
      - wireshark
      - ninja-build
      - gettext
      - cmake
      - apt-file
      - xbindkeys
      - whois
      - dnsutils
      - libpam-yubico
      - libyubikey-dev
      - yubikey-personalization
      - yubikey-luks
      - yubikey-manager
      - libpam-u2f
      - pcscd
      - libbz2-dev
      - libncurses-dev
      - libffi-dev
      - libreadline-dev
      - libsqlite3-dev
        #- libzma-dev
      - tk-dev
      - libasound2-dev
      - libudev-dev
      - kitty
      - kitty-doc
      - kitty-terminfo
  - name: dark gnome
    become_user: matt
    community.general.dconf:
      key: /org/gnome/desktop/interface/gtk-theme
      value: "'Adwaita-dark'"
      state: present
  - name: dark gnome terminal
    become_user: matt
    community.general.dconf:
      key: /org/gnome/terminal/legacy/theme-variant
      value: "'dark'"
  - name: mouse natural direction
    become_user: matt
    community.general.dconf:
      key: /org/gnome/desktop/peripherals/mouse/natural-scroll
      value: 'true'
  - name: dark gnome terminal
    become_user: matt
    community.general.dconf:
      key: /org/gnome/desktop/peripherals/mouse/natural-scroll
      value: 'true'
  - name: automatic brightness off
    become_user: matt
    community.general.dconf:
      key: /org/gnome/settings-daemon/plugins/power/ambient-enabled
      value: 'false'
  - name: automatic suspend off
    become_user: matt
    community.general.dconf:
      key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
      value: "'nothing'"
  - name: blank screen 15 minutes
    become_user: matt
    community.general.dconf:
      key: /org/gnome/desktop/session/idle-delay/
      value: "uint32 900"
  - name: brightness up
    become_user: matt
    community.general.dconf:
      key: /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-up
      value: "['F12']" 
  - name: brightness down
    become_user: matt
    community.general.dconf:
      key: /org/gnome/settings-daemon/plugins/media-keys/screen-brightness-down
      value: "['F11']" 
  - name: git dotfiles
    ansible.builtin.git:
      repo: https://github.com/woodroww/.dotfiles.git 
      dest: /home/matt/.dotfiles
  - name: clock am pm gnome
    become_user: matt
    community.general.dconf:
      key: /org/gnome/desktop/interface/clock-format
      value: "12h" 
  - name: clock am pm gtk
    become_user: matt
    community.general.dconf:
      key: /org/gtk/settings/file-chooser/clock-format
      value: "12h"
