- hosts: localhost
  gather_facts: true
  tasks:
  - name: check if cargo is installed
    become_user: matt
    shell: command -v cargo
    register: cargo_exists
    ignore_errors: yes

  - name: Download Installer
    become_user: matt
    when: cargo_exists is failed
    get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'
    tags:
      - rust

  - name: install rust/cargo
    become_user: matt
    when: cargo_exists is failed
    shell: /tmp/sh.rustup.rs -y
    tags:
      - rust
